# Generated by Django 6.0.5 on 2026-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('logo1', models.ImageField(upload_to='teams/')),
                ('logo2', models.ImageField(upload_to='teams/')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('prediction', models.TextField()),
                ('is_today_match', models.BooleanField(default=False)),
                ('prediction_locked', models.BooleanField(default=True)),
            ],
        ),
    ]
