# Generated by Django 6.0.5 on 2026-06-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_match_prediction_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='confidence_team1',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='match',
            name='confidence_team2',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='match',
            name='prediction_lock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='reason1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='reason2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='reason3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
