# Generated by Django 6.0.5 on 2026-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leaderboard_predictionaccuracy_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='Cricket', max_length=50),
        ),
    ]
